movie_project/movieproject/movieapp/urls.py
from django.urls import path
from .import views
app_name = 'movieapp'

urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.details,name='details'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]

movie_project/movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root = settings.MEDIA_ROOT)

movie_project/movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movie_project/movieproject/movieapp/forms.py
from django import forms
from .models import Movie
class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields =['name','desc','year','img']

movie_project/movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm
# Create your views here.
def index(request):
    movie = Movie.objects.all()
    context = {
        'movie_list':movie
    }
    return render(request,'index.html',context)
def details(request,movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request,'details.html',{'movie':movie})

def add_movie(request):
    if request.method == 'POST':
        name = request.POST['name']
        desc = request.POST['desc']
        year = request.POST['year']
        img = request.FILES['img']
        movie = Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,'add.html')
def update(request,id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None, request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})
def delete(request,id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movie_project/movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
    <div style="padding:50px;text-align:center;">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="text" name="name" placeholder="Enter your Movie name"><br><br>
            <input type="text" name="desc" placeholder="Enter your Movie desc"><br><br>
            <input type="text" name="year" placeholder="Enter your Movie year"><br><br>
             <input type="file" name="img"><br><br>
            <input type="submit">
        </form>
        {% endblock %}
    </div>

movie_project/movieproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
    <body>

        <nav class="navbar navbar-dark bg-dark">
            <a class="navbar-brand" href="#">
                Online Movie Store
            </a>
        </nav>
    {% block body %}
    {% endblock %}
    </body>
</html>

movie_project/movieproject/templates/delete.html
<div style="padding:50px; text-align:center;">
  <form method="post">
    {% csrf_token %}
    <h3>Are you want to delete this movie?<h3><br>
    <input type="submit">
  </form>
</div>

movie_project/movieproject/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row" style="padding:80px">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="300"><br>
        </div>
        <div class="col-md-6" style="text-align:center;">
            <h2>{{movie.name}}</h2>
            <h5>{{movie.desc}}</h5>
            <h6>{{movie.year}}</h6><br>
            <a class="bin btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a><br><br>
            <a class="btn btn-danger"  href="{% url 'movieapp:delete' movie.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

movie_project/movieproject/templates/edit.html
<div style="text-align:center;padding:30px;">
    <h2>Update</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit">
    </form>
</div>

movie_project/movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}


<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 15rem height:15rem; padding:10px">
                <img class="card-img-top" src="{{ i.img.url }}" width="100px height=100px";>
                    <div class="card-body">
                        <h5 class="card-title">{{ i.name }}</h5>
                        <p class="card-text">{{i.desc}}</p>
                        <a href="{% url 'movieapp:details' i.id %}" class="btn btn-primary">Go moredetails..</a>
                    </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}