banking/bankproject/bank/urls.py
from django.urls import path
from .import views
app_name='bank'


urlpatterns = [
    path('',views.index,name='index'),

]

banking/bankproject/bankproject/urls.py
from django.contrib import admin
from django.urls import path, include
from bankproject import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bank.urls')),
    path('credence/',include('credential.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

banking/bankproject/credential/urls.py
from .import views
from django.urls import path
app_name='credential'

urlpatterns =[
    path('register',views.register,name='register'),
    path('login',views.loginn,name='login'),
    path('logout',views.logout,name='logout'),
    path('welcome',views.welcome,name='welcome'),
    path('success',views.success,name='success'),
    path('details',views.detail_form,name='detail_form'),
]

banking/bankproject/bank/models.py
from django.db import models

# Create your models here.

banking/bankproject/credential/models.py
from django.db import models

# Create your models here.

banking/bankproject/bank/views.py
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
# Index
def index(request):
    return render(request,'index.html')

# DetailForm

banking/bankproject/credential/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.contrib import messages,auth
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login

# Create your views here.

def loginn(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username,password=password)

        if user is not None:
            login(request,user)
            return render(request,'welcome.html')
        else:
            return render(request,'login.html')

    return render(request,'login.html')
def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        cpassword = request.POST['cpassword']
        if password == cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'Username Taken')
            else:
                myuser = User.objects.create_user(username=username,password=password)
                myuser.save()
                return render(request,'login.html')
        else:
            messages.info(request,'Password not matching')

            return render(request,'register.html')

    return render(request,'register.html')

def logout(request):
    auth.logout(request)
    return redirect('/')

def welcome(request):
    return render(request,'welcome.html')


def success(request):
    return render(request,'success.html')


def detail_form(request):
    if request.method == 'POST':
        uname = request.POST.get('uname')
        dob = request.POST.get('dob')
        age = request.POST.get('age')
        gender = request.POST.get('gender')
        phone_number = request.POST.get('phone_number')
        email = request.POST.get('email')
        address = request.POST.get('address')
        district = request.POST.get('district')
        branch = request.POST.get('branch')
        account_type = request.POST.get('account_type')
        material = request.POST.get('material')
        user_data = User.objects.all()
        return render(request,'success.html')
    return render(request,'details.html')

banking/bankproject/templates/details.html
<!DOCTYPE html>
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/detailstyle.css' %}">
    <title>Details</title>
</head>
<body>

<div class="container">
    <h2>Detail Form</h2>

    <form method="post" action="details" onsubmit="return validate()">
        {% csrf_token %}
        <div class="form-group">
            <label for="uname">Name:</label>
            <input type="text"  id="uname" name="uname" required>
        </div>

        <div class="form-group">
            <label for="dob">Date of Birth:</label>
            <input type="date" id="dob" name="dob" required>
        </div>

        <div class="form-group">
            <label for="age">Age:</label>
            <input type="number" id="age" name="age" required>
        </div>

        <div class="form-group">
            <label>Gender:</label>
            <input type="radio" id="gender1" name="gender" value="Male" required> Male
            <input type="radio" id="gender2"  name="gender" value="Female" required> Female
            <input type="radio" id="gender3"  name="gender" value="Other" required> Other
        </div>

        <div class="form-group">
            <label for="phonenumber">Phone Number:</label>
            <input type="tel" id="phonenumber" name="phone_number" required>
        </div>

        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required>
        </div>

        <div class="form-group">
            <label for="address">Address:</label>
            <textarea name="address" id="address" rows="4" required></textarea>
        </div>

        <div class="form-group">
            <label for="district">District:</label>
                <select id="district" onchange="populateBranches()" required>
                    <option value="" selected disabled> Select district </option>
                    <option value="kollam">Kollam</option>
                    <option value="alappuzha">Alappuzha</option>
                    <option value="kottayam">Kottayam</option>
                    <option value="idukki">Idukki</option>
                    <option value="ernakulam">Ernakulam</option>
                    <option value="palakkad">Palakkad</option>
                    <option value="kozhikode">Kozhikode</option>
                    <option value="kannur">Kannur</option>
                </select>
            <br><br>
            <label for="branch">Branch:</label>
                <select id="branch" required>
                    <option value="" selected disabled> Select branch </option>
                </select>
        <script>
            var branches={
                kollam:["Ashtamudi","Punalur","Oachira"],
                alappuzha:["Kayamkulam","Kuttanad","Cherthala"],
                kottayam:["Changanassery","Pala","Vaikom"],
                idukki:["Thodupuzha","Devikulam","Vandiperiyar"],
                ernakulam:["Aluva","Angamaly","Kochi"],
                palakkad:["Ottapalam","Alathur","Chittur"],
                kozhikode:["Beypore","Pantheeramkavu","Feroke"],
                kannur:["Ezhimala","Payyambalami","Kuthuparamba"],
                };
            var districtSelect = document.getElementById("district");
            var branchSelect = document.getElementById("branch");

            function populateBranches(){
                branchSelect.innerHTML = '<option value=""> Select a state</option>';

                var selectedDistrict = districtSelect.value;
                if(selectedDistrict){
                    var selectedBranches = branches[selectedDistrict];
                    selectedBranches.forEach(function(branch){
                        var option = document.createElement("option");
                        option.value = branch;
                        option.text = branch;
                        branchSelect.appendChild(option);
                    });
                }
            }
        </script>

        </div>

        <div class="form-group">
            <label for="account_type">Account type:</label>
            <select id="account_type" name="account_type" required>
                <option value="" disabled selected>Select Account Type</option>
                <option value="Savings">Savings</option>
                <option value="Current">Current</option>
                <option value="Salary">Salary</option>
                <option value="Fixed deposit">Fixed deposit</option>
            </select>
        </div>

        <div class="form-group">
            <label>Materials provide:</label>
            <input type="checkbox" id="material1" name="material" value="Credit"> Credit Card
            <input type="checkbox" id="material2"  name="material" value="Debit"> Debit Card
            <input type="checkbox" id="material3" name="material" value="Cheque"> Cheque Book

            <script>

                function validate(){
                    var valid = false;
                    if(document.getElementById("material1").checked){
                        valid = true;
                    }
                    else if(document.getElementById("material2").checked){
                        valid = true;
                    }
                    else if(document.getElementById("material3").checked){
                        valid = true;
                    }
                    else{
                        alert("Please select at least one ")
                        return false;
                    }
                }

            </script>

        </div>



        <div>
            <a href="success"><button  onclick="valCheckbox()"  style="background-color: green; color: white;">Submit</button></a>
        </div>
        <br>
    </form>

    <div style="text-align:center;">
         Back to home? <a href="/">Home</a>
    </div>
</div>
</body>
</html>

banking/bankproject/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
   <head>
      <meta charset="utf-8">
      <title>Login</title>
      <link rel="stylesheet" href="{% static 'css/loginstyle.css' %}">
   </head>
   <body>
      <div class="wrapper">
         <div class="title">
            User Login
         </div>
         <form action="login" method="post">
            {% csrf_token %}
            <div class="field">
               <input type="text" id="username" name="username" required>
               <label>Username</label>
            </div>
            <div class="field">
               <input type="password" id="password" name="password"  required>
               <label>Password</label>
            </div>
            <div class="content">
               <div class="checkbox">
                  <input type="checkbox" id="remember-me" name="checkbox">
                  <label for="remember-me">Remember me</label>
               </div>
               <div class="pass-link">
                  <a href="#">Forgot password?</a>
               </div>
            </div>
            <div class="field">
                <input type="submit" value="Login">
               <!-- <button type="submit">login</button> -->
            </div>
            <div class="signup-link">
               Don't have an account? <a href="{% url 'credential:register' %}">Register now</a>
            </div>
         </form>
      </div>
</body>
</html>

banking/bankproject/templates/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <title>Register</title>
    <link rel="stylesheet" href="{% static 'css/registerstyle.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body>
  <div class="container">
        <div class="cover">
            <div class="front">
                <img src="{% static 'images/frontImg.jpg' %}" alt="">
                <div class="text">
                    <span class="text-1">New User Registration<br></span>
                    <span class="text-2">Let's get connected</span>
                </div>
            </div>
        </div>
        <div class="forms">
            <div class="form-content">
                <div class="login-form">
                    <div class="title">Register</div>
                    <form action="#" method="post">
                        {% csrf_token %}
                        <div class="input-boxes">
                            <div class="input-box">
                                <i class="fas fa-user"></i>
                                <input type="text" placeholder="Enter your Username" id="username" name="username" required>
                            </div>
                            <div class="input-box">
                                <i class="fas fa-lock"></i>
                                <input type="password" placeholder="Enter your password" id="password" name="password" required>
                            </div>
                            <div class="input-box">
                                <i class="fas fa-lock"></i>
                                <input type="password" placeholder="Enter your confirmpassword" id="cpassword" name="cpassword" required>
                            </div>
                            <div class="button input-box">
                                <!-- <button type="submit">Submit</button> -->
                                <input type="submit" value="Submit">
                            </div>
                        </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
  </div>
</body>
</html>

banking/bankproject/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>success</title>
</head>
<body style="background-color:gray">
    <div style="padding:150px;text-align:center">
        <h3>Form accepted....</h3>
        <h2> Back to Home</h2>
        <div>
            <a href="logout"><button style="background-color: GoldenRod; color: white;">Logout</button></a>
        </div>
    </div>
</body>
</html>

banking/bankproject/templates/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome</title>
</head>
<body style="background-color:gray">
    <div style="padding:150px;text-align:center">
        <h3>Welcome User</h3>
        <h2>Please click on the below button </h2>
        <a href="details" target="">
        <button style="background-color: GoldenRod; color: white;">Click Me!</button>
        </a>
    </div>
</body>
</html>