todo_project/todoproject/todoapp/urls.py
from django.urls import path
from .import views
app_name='todoapp'
urlpatterns = [
    path('',views.add,name='add'),
    path('delete/<int:taskid>/',views.delete,name='delete'),
    path('update/<int:id>/',views.update,name='update'),
]

todo_project/todoproject/todoproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

todo_project/todoproject/todoapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name=models.CharField(max_length=250)
    priority=models.IntegerField()
    date=models.DateField()

    def __str__(self):
        return self.name

todo_project/todoproject/todoapp/forms.py
from . models import Task
from django import forms

class TodoForm(forms.ModelForm):
    class Meta:
        model=Task
        fields=['name','priority','date']

todo_project/todoproject/todoapp/views.py
from django.shortcuts import render, redirect
from .models import Task
from .forms import TodoForm



# Create your views here.

# Add
def add(request):
    task1 = Task.objects.all()
    if request.method == 'POST':
        name = request.POST.get('task', '')
        priority = request.POST.get('priority')
        date = request.POST.get('date', '')
        task = Task(name=name, priority=priority, date=date)
        task.save()
    return render(request, 'home.html', {'task1': task1})

# Delete
def delete(request, taskid):
    task = Task.objects.get(id=taskid)
    if request.method == 'POST':
        task.delete()
        return redirect('/')
    return render(request, 'delete.html')

# Update
def update(request, id):
    task = Task.objects.get(id=id)
    f = TodoForm(request.POST or None, instance=task)
    if f.is_valid():
        f.save()
        return redirect('/')
    return render(request, 'edit.html', {'f': f, 'task': task})

todo_project/todoproject/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

todo_project/todoproject/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
  {% csrf_token %}
  <p>Are you sure this task is done ?</p>
  <button type="submit">Confirm</button>
</form>
{% endblock %}

todo_project/todoproject/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<div class="card">
    <div class="card-header">
        <div class="card-title">
            Task Update
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{f.as_p}}
                <button type="submit">Confirm</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

todo_project/todoproject/templates/home.html
{% extends 'base.html' %}
{% block content %}
<!-- Banner -->
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>TODO</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Task-->
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="post" class="p-3 shadow">
                {% csrf_token %}
                <div class="form-group">
                     <input type="text" class="form-control" name="task" placeholder="Enter your task name">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="priority" placeholder="Enter your priority">
                </div>
                <div class="form-group">
                    <input type="date" class="form-control" name="date" placeholder="Enter your date">
                </div>
                <input type="submit" class="btn btn-success">
            </form>
        </div>
        <!--Task completed -->
        <div class="col-md-6">
            <h6> Task to be completed </h6>
            {% for i in task1 %}
                <div class="shadow card">
                    <div class="card-body">
                        <h5 class="card-title">{{i.name}}</h5>
                        <p><br>{{i.priority}}<br></p>
                        <p><br>{{i.date}}<br></p>
                        <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">Delete</a>
                        <a class="btn btn-success" href="{% url 'todoapp:update' i.id %}">Update</a>
                    </div>
                </div>
                <br>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}